export const GET_NOTES_SUCESS = "GET_NOTES_SUCCESS";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const SIDEBAR_CLICK_SUCCESS = "SIDEBAR_CLICK_SUCCESS";
export const EDIT_CLICK_SUCCESS = "EDIT_CLICK_SUCCESS";
export const CANCEL_EDIT_SUCCESS = "CANCEL_EDIT_SUCCESS";
export const SEARCH_NOTES_SUCCESS ="SEARCH_NOTES_SUCCESS";

